### PR TITLE
Fix jsdom 2

### LINKED ISSUE #243: TypeError: Cannot set property performance of #<Object> which has only a getter
* Lolex version : 4.0.1
* Environment   : node@10.15.1
* Other libraries you are using: 
  - jsdom@15.1.0

This is an issue that was raised before as #197. That issue links to code changes that would probably fix this issue.  However, those changes never appeared to have made it to `master`.

**What did you expect to happen?**
Lolex to initialize without error

**What actually happens**
I get the stack trace:
```
/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:451
            target[method] = clock[method];
                           ^

TypeError: Cannot set property performance of #<Object> which has only a getter
    at hijackMethod (/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:451:28)
    at Object.install (/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:923:17)
    at Object.<anonymous> (/Users/cdow2/workspace/lolex-test/index.js:35:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**How to reproduce**
I'm trying to use the jsdom setup for enzyme described [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md).  This can be reproduced by creating an node project with the following files:

<details>
    <summary>package.json</summary>

```json
{
  "name": "lolex-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jsdom": "^15.1.0",
    "lolex": "^4.0.1"
  }
}
```
</details>

<details>
    <summary>index.js</summary>

```js

//
// Setup described in: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
//
const { JSDOM } = require('jsdom');

const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  });
}

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function (callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function (id) {
  clearTimeout(id);
};
copyProps(window, global);

//
// Main code
//
const lolex = require('lolex');
const clock = lolex.install();
clock.uninstall();
```
</details>

Then run the following commands:
```
npm install
npm start
```

### PR DESCRIPTION
**Pull request by cdow**
#### Purpose (TL;DR) - mandatory

Fix #243 by changing the way the `performance` field gets overwritten.  This time without breaking some browsers.

#### Background (Problem in detail)  - optional

JSDOM has a read only `performance` field.  So, when JSDOM is configured to provide [global values](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md), lolex will error on init. This is because it can't overwrite the global `performance` field.

### CODE REVIEW

File: integration-test/lolex-integration-test.js [hunk 1]
```diff
@@ -57,3 +57,83 @@ describe("withGlobal", function () {
         clock.uninstall();
     });
 });
+
+describe("globally configured browser objects", function () {
+    var withGlobal, originalDescriptors;
+
+    // Used to support Node 6 which doesn't support Object.getOwnPropertyDescriptors
```
Comment (fatso83) [inline integration-test/lolex-integration-test.js]: I'll try to fix the issues in #87 so this won't be needed.

But thank you for good comments!

File: integration-test/lolex-integration-test.js [hunk 2]
```diff
@@ -57,3 +57,83 @@ describe("withGlobal", function () {
...
+        };
+        global.requestAnimationFrame = function (callback) {
+            return setTimeout(callback, 0);
+        };
+        global.cancelAnimationFrame = function (id) {
+            clearTimeout(id);
+        };
+        copyProps(window, global);
+
+        withGlobal = lolex.withGlobal(global);
```
Comment (fatso83) [inline integration-test/lolex-integration-test.js]: :+1:
